/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolverDynDoorObstacle1_model_ ## ID
#endif

#include <math.h> 
#include "FORCESNLPsolverDynDoorObstacle1_model.h"

#ifndef casadi_real
#define casadi_real FORCESNLPsolverDynDoorObstacle1_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[20] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[25] = {3, 10, 0, 0, 0, 0, 3, 6, 9, 12, 12, 12, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[12] = {4, 6, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s9[12] = {6, 6, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5};
static const casadi_int casadi_s10[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* FORCESNLPsolverDynDoorObstacle1_objective_0:(i0[10],i1[36])->(o0,o1[1x10,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_objective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_objective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_objective_0_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_objective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_objective_0_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_objective_0_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_objective_0_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_objective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynDoorObstacle1_objective_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynDoorObstacle1_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynDoorObstacle1_inequalities_0:(i0[10],i1[36])->(o0[3],o1[3x10,12nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a7, a8, a9;
  a0=arg[1]? arg[1][10] : 0;
  a1=casadi_sq(a0);
  a2=arg[1]? arg[1][11] : 0;
  a3=casadi_sq(a2);
  a4=(a1-a3);
  a5=arg[1]? arg[1][12] : 0;
  a6=casadi_sq(a5);
  a4=(a4-a6);
  a7=arg[1]? arg[1][9] : 0;
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a9=arg[0]? arg[0][4] : 0;
  a10=arg[1]? arg[1][6] : 0;
  a10=(a9-a10);
  a11=(a4*a10);
  a12=2.;
  a13=(a0*a2);
  a14=(a5*a7);
  a15=(a13-a14);
  a15=(a12*a15);
  a16=arg[0]? arg[0][5] : 0;
  a17=arg[1]? arg[1][7] : 0;
  a17=(a16-a17);
  a18=(a15*a17);
  a11=(a11+a18);
  a18=(a0*a5);
  a19=(a2*a7);
  a20=(a18+a19);
  a20=(a12*a20);
  a21=arg[0]? arg[0][6] : 0;
  a22=arg[1]? arg[1][8] : 0;
  a22=(a21-a22);
  a23=(a20*a22);
  a11=(a11+a23);
  a23=fabs(a11);
  a24=arg[1]? arg[1][13] : 0;
  a25=5.5000000000000000e-02;
  a24=(a24+a25);
  a26=2.0000000000000000e-02;
  a24=(a24+a26);
  a23=(a23/a24);
  a27=6.;
  a28=(a27*a23);
  a28=exp(a28);
  a29=(a23*a28);
  a13=(a13+a14);
  a13=(a12*a13);
  a14=(a13*a10);
  a30=(a3-a1);
  a30=(a30-a6);
  a30=(a30+a8);
  a31=(a30*a17);
  a14=(a14+a31);
  a2=(a2*a5);
  a0=(a0*a7);
  a7=(a2-a0);
  a7=(a12*a7);
  a5=(a7*a22);
  a14=(a14+a5);
  a5=fabs(a14);
  a31=arg[1]? arg[1][14] : 0;
  a32=5.0000000000000003e-02;
  a31=(a31+a32);
  a31=(a31+a26);
  a5=(a5/a31);
  a33=(a27*a5);
  a33=exp(a33);
  a34=(a5*a33);
  a29=(a29+a34);
  a18=(a18-a19);
  a18=(a12*a18);
  a10=(a18*a10);
  a2=(a2+a0);
  a12=(a12*a2);
  a17=(a12*a17);
  a10=(a10+a17);
  a1=(a1+a3);
  a6=(a6-a1);
  a6=(a6+a8);
  a22=(a6*a22);
  a10=(a10+a22);
  a22=fabs(a10);
  a8=arg[1]? arg[1][15] : 0;
  a22=(a22/a8);
  a1=(a27*a22);
  a1=exp(a1);
  a3=(a22*a1);
  a29=(a29+a3);
  a3=(a27*a23);
  a3=exp(a3);
  a17=(a27*a5);
  a17=exp(a17);
  a2=(a3+a17);
  a0=(a27*a22);
  a0=exp(a0);
  a2=(a2+a0);
  a29=(a29/a2);
  a19=arg[0]? arg[0][3] : 0;
  a34=(a29+a19);
  if (res[0]!=0) res[0][0]=a34;
  a34=arg[1]? arg[1][16] : 0;
  a34=(a9-a34);
  a35=fabs(a34);
  a36=arg[1]? arg[1][23] : 0;
  a36=(a36+a25);
  a36=(a36+a26);
  a35=(a35/a36);
  a37=(a27*a35);
  a37=exp(a37);
  a38=(a35*a37);
  a39=arg[1]? arg[1][17] : 0;
  a39=(a16-a39);
  a40=fabs(a39);
  a41=arg[1]? arg[1][24] : 0;
  a41=(a41+a32);
  a41=(a41+a26);
  a40=(a40/a41);
  a42=(a27*a40);
  a42=exp(a42);
  a43=(a40*a42);
  a38=(a38+a43);
  a43=arg[1]? arg[1][18] : 0;
  a43=(a21-a43);
  a44=fabs(a43);
  a45=arg[1]? arg[1][25] : 0;
  a45=(a45+a26);
  a44=(a44/a45);
  a46=(a27*a44);
  a46=exp(a46);
  a47=(a44*a46);
  a38=(a38+a47);
  a47=(a27*a35);
  a47=exp(a47);
  a48=(a27*a40);
  a48=exp(a48);
  a49=(a47+a48);
  a50=(a27*a44);
  a50=exp(a50);
  a49=(a49+a50);
  a38=(a38/a49);
  a51=(a38+a19);
  if (res[0]!=0) res[0][1]=a51;
  a51=arg[1]? arg[1][26] : 0;
  a9=(a9-a51);
  a51=fabs(a9);
  a52=arg[1]? arg[1][33] : 0;
  a52=(a52+a25);
  a51=(a51/a52);
  a25=(a27*a51);
  a25=exp(a25);
  a53=(a51*a25);
  a54=arg[1]? arg[1][27] : 0;
  a16=(a16-a54);
  a54=fabs(a16);
  a55=arg[1]? arg[1][34] : 0;
  a55=(a55+a32);
  a54=(a54/a55);
  a32=(a27*a54);
  a32=exp(a32);
  a56=(a54*a32);
  a53=(a53+a56);
  a56=arg[1]? arg[1][28] : 0;
  a21=(a21-a56);
  a56=fabs(a21);
  a57=arg[1]? arg[1][35] : 0;
  a57=(a57+a26);
  a56=(a56/a57);
  a26=(a27*a56);
  a26=exp(a26);
  a58=(a56*a26);
  a53=(a53+a58);
  a58=(a27*a51);
  a58=exp(a58);
  a59=(a27*a54);
  a59=exp(a59);
  a60=(a58+a59);
  a61=(a27*a56);
  a61=exp(a61);
  a60=(a60+a61);
  a53=(a53/a60);
  a19=(a53+a19);
  if (res[0]!=0) res[0][2]=a19;
  a19=1.;
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a19;
  if (res[1]!=0) res[1][2]=a19;
  a11=casadi_sign(a11);
  a4=(a11*a4);
  a4=(a4/a24);
  a19=(a28*a4);
  a62=(a27*a4);
  a62=(a28*a62);
  a62=(a23*a62);
  a19=(a19+a62);
  a14=casadi_sign(a14);
  a13=(a14*a13);
  a13=(a13/a31);
  a62=(a33*a13);
  a63=(a27*a13);
  a63=(a33*a63);
  a63=(a5*a63);
  a62=(a62+a63);
  a19=(a19+a62);
  a10=casadi_sign(a10);
  a18=(a10*a18);
  a18=(a18/a8);
  a62=(a1*a18);
  a63=(a27*a18);
  a63=(a1*a63);
  a63=(a22*a63);
  a62=(a62+a63);
  a19=(a19+a62);
  a19=(a19/a2);
  a29=(a29/a2);
  a4=(a27*a4);
  a4=(a3*a4);
  a13=(a27*a13);
  a13=(a17*a13);
  a4=(a4+a13);
  a18=(a27*a18);
  a18=(a0*a18);
  a4=(a4+a18);
  a4=(a29*a4);
  a19=(a19-a4);
  if (res[1]!=0) res[1][3]=a19;
  a34=casadi_sign(a34);
  a34=(a34/a36);
  a36=(a37*a34);
  a19=(a27*a34);
  a37=(a37*a19);
  a35=(a35*a37);
  a36=(a36+a35);
  a36=(a36/a49);
  a38=(a38/a49);
  a34=(a27*a34);
  a47=(a47*a34);
  a47=(a38*a47);
  a36=(a36-a47);
  if (res[1]!=0) res[1][4]=a36;
  a9=casadi_sign(a9);
  a9=(a9/a52);
  a52=(a25*a9);
  a36=(a27*a9);
  a25=(a25*a36);
  a51=(a51*a25);
  a52=(a52+a51);
  a52=(a52/a60);
  a53=(a53/a60);
  a9=(a27*a9);
  a58=(a58*a9);
  a58=(a53*a58);
  a52=(a52-a58);
  if (res[1]!=0) res[1][5]=a52;
  a15=(a11*a15);
  a15=(a15/a24);
  a52=(a28*a15);
  a58=(a27*a15);
  a58=(a28*a58);
  a58=(a23*a58);
  a52=(a52+a58);
  a30=(a14*a30);
  a30=(a30/a31);
  a58=(a33*a30);
  a9=(a27*a30);
  a9=(a33*a9);
  a9=(a5*a9);
  a58=(a58+a9);
  a52=(a52+a58);
  a12=(a10*a12);
  a12=(a12/a8);
  a58=(a1*a12);
  a9=(a27*a12);
  a9=(a1*a9);
  a9=(a22*a9);
  a58=(a58+a9);
  a52=(a52+a58);
  a52=(a52/a2);
  a15=(a27*a15);
  a15=(a3*a15);
  a30=(a27*a30);
  a30=(a17*a30);
  a15=(a15+a30);
  a12=(a27*a12);
  a12=(a0*a12);
  a15=(a15+a12);
  a15=(a29*a15);
  a52=(a52-a15);
  if (res[1]!=0) res[1][6]=a52;
  a39=casadi_sign(a39);
  a39=(a39/a41);
  a41=(a42*a39);
  a52=(a27*a39);
  a42=(a42*a52);
  a40=(a40*a42);
  a41=(a41+a40);
  a41=(a41/a49);
  a39=(a27*a39);
  a48=(a48*a39);
  a48=(a38*a48);
  a41=(a41-a48);
  if (res[1]!=0) res[1][7]=a41;
  a16=casadi_sign(a16);
  a16=(a16/a55);
  a55=(a32*a16);
  a41=(a27*a16);
  a32=(a32*a41);
  a54=(a54*a32);
  a55=(a55+a54);
  a55=(a55/a60);
  a16=(a27*a16);
  a59=(a59*a16);
  a59=(a53*a59);
  a55=(a55-a59);
  if (res[1]!=0) res[1][8]=a55;
  a11=(a11*a20);
  a11=(a11/a24);
  a24=(a28*a11);
  a20=(a27*a11);
  a28=(a28*a20);
  a23=(a23*a28);
  a24=(a24+a23);
  a14=(a14*a7);
  a14=(a14/a31);
  a31=(a33*a14);
  a7=(a27*a14);
  a33=(a33*a7);
  a5=(a5*a33);
  a31=(a31+a5);
  a24=(a24+a31);
  a10=(a10*a6);
  a10=(a10/a8);
  a8=(a1*a10);
  a6=(a27*a10);
  a1=(a1*a6);
  a22=(a22*a1);
  a8=(a8+a22);
  a24=(a24+a8);
  a24=(a24/a2);
  a11=(a27*a11);
  a3=(a3*a11);
  a14=(a27*a14);
  a17=(a17*a14);
  a3=(a3+a17);
  a10=(a27*a10);
  a0=(a0*a10);
  a3=(a3+a0);
  a29=(a29*a3);
  a24=(a24-a29);
  if (res[1]!=0) res[1][9]=a24;
  a43=casadi_sign(a43);
  a43=(a43/a45);
  a45=(a46*a43);
  a24=(a27*a43);
  a46=(a46*a24);
  a44=(a44*a46);
  a45=(a45+a44);
  a45=(a45/a49);
  a43=(a27*a43);
  a50=(a50*a43);
  a38=(a38*a50);
  a45=(a45-a38);
  if (res[1]!=0) res[1][10]=a45;
  a21=casadi_sign(a21);
  a21=(a21/a57);
  a57=(a26*a21);
  a45=(a27*a21);
  a26=(a26*a45);
  a56=(a56*a26);
  a57=(a57+a56);
  a57=(a57/a60);
  a27=(a27*a21);
  a61=(a61*a27);
  a53=(a53*a61);
  a57=(a57-a53);
  if (res[1]!=0) res[1][11]=a57;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_0_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_0_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_0_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_0_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_inequalities_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynDoorObstacle1_inequalities_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynDoorObstacle1_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynDoorObstacle1_cdyn_0:(i0[6],i1[4],i2[36])->(o0[6],o1[4x6,3nz],o2[6x6,3nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_cdyn_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolverDynDoorObstacle1_cdyn_0_n_out(void) { return 3;}

casadi_real FORCESNLPsolverDynDoorObstacle1_cdyn_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_cdyn_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_cdyn_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_cdyn_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_cdyn_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0:(i0[6],i1[4],i2[36])->(o0[6]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_cdyn_0rd_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynDoorObstacle1_objective_1:(i0[10],i1[36])->(o0,o1[1x10]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  a11=1.0000000000000001e-01;
  a12=arg[0]? arg[0][7] : 0;
  a13=casadi_sq(a12);
  a13=(a11*a13);
  a2=(a2+a13);
  a13=arg[0]? arg[0][8] : 0;
  a14=casadi_sq(a13);
  a14=(a11*a14);
  a2=(a2+a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=casadi_sq(a14);
  a15=(a11*a15);
  a2=(a2+a15);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  a12=(a12+a12);
  a12=(a11*a12);
  if (res[1]!=0) res[1][7]=a12;
  a13=(a13+a13);
  a13=(a11*a13);
  if (res[1]!=0) res[1][8]=a13;
  a14=(a14+a14);
  a11=(a11*a14);
  if (res[1]!=0) res[1][9]=a11;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_objective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_objective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_objective_1_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_objective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_objective_1_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_objective_1_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_objective_1_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_objective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynDoorObstacle1_objective_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynDoorObstacle1_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s10;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynDoorObstacle1_inequalities_1:(i0[10],i1[36])->(o0[3],o1[3x10,12nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a52, a53, a54, a55, a56, a57, a58, a59, a6, a60, a61, a62, a63, a7, a8, a9;
  a0=arg[1]? arg[1][10] : 0;
  a1=casadi_sq(a0);
  a2=arg[1]? arg[1][11] : 0;
  a3=casadi_sq(a2);
  a4=(a1-a3);
  a5=arg[1]? arg[1][12] : 0;
  a6=casadi_sq(a5);
  a4=(a4-a6);
  a7=arg[1]? arg[1][9] : 0;
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a9=arg[0]? arg[0][4] : 0;
  a10=arg[1]? arg[1][6] : 0;
  a10=(a9-a10);
  a11=(a4*a10);
  a12=2.;
  a13=(a0*a2);
  a14=(a5*a7);
  a15=(a13-a14);
  a15=(a12*a15);
  a16=arg[0]? arg[0][5] : 0;
  a17=arg[1]? arg[1][7] : 0;
  a17=(a16-a17);
  a18=(a15*a17);
  a11=(a11+a18);
  a18=(a0*a5);
  a19=(a2*a7);
  a20=(a18+a19);
  a20=(a12*a20);
  a21=arg[0]? arg[0][6] : 0;
  a22=arg[1]? arg[1][8] : 0;
  a22=(a21-a22);
  a23=(a20*a22);
  a11=(a11+a23);
  a23=fabs(a11);
  a24=arg[1]? arg[1][13] : 0;
  a25=5.5000000000000000e-02;
  a24=(a24+a25);
  a26=2.0000000000000000e-02;
  a24=(a24+a26);
  a23=(a23/a24);
  a27=6.;
  a28=(a27*a23);
  a28=exp(a28);
  a29=(a23*a28);
  a13=(a13+a14);
  a13=(a12*a13);
  a14=(a13*a10);
  a30=(a3-a1);
  a30=(a30-a6);
  a30=(a30+a8);
  a31=(a30*a17);
  a14=(a14+a31);
  a2=(a2*a5);
  a0=(a0*a7);
  a7=(a2-a0);
  a7=(a12*a7);
  a5=(a7*a22);
  a14=(a14+a5);
  a5=fabs(a14);
  a31=arg[1]? arg[1][14] : 0;
  a32=5.0000000000000003e-02;
  a31=(a31+a32);
  a31=(a31+a26);
  a5=(a5/a31);
  a33=(a27*a5);
  a33=exp(a33);
  a34=(a5*a33);
  a29=(a29+a34);
  a18=(a18-a19);
  a18=(a12*a18);
  a10=(a18*a10);
  a2=(a2+a0);
  a12=(a12*a2);
  a17=(a12*a17);
  a10=(a10+a17);
  a1=(a1+a3);
  a6=(a6-a1);
  a6=(a6+a8);
  a22=(a6*a22);
  a10=(a10+a22);
  a22=fabs(a10);
  a8=arg[1]? arg[1][15] : 0;
  a22=(a22/a8);
  a1=(a27*a22);
  a1=exp(a1);
  a3=(a22*a1);
  a29=(a29+a3);
  a3=(a27*a23);
  a3=exp(a3);
  a17=(a27*a5);
  a17=exp(a17);
  a2=(a3+a17);
  a0=(a27*a22);
  a0=exp(a0);
  a2=(a2+a0);
  a29=(a29/a2);
  a19=arg[0]? arg[0][3] : 0;
  a34=(a29+a19);
  if (res[0]!=0) res[0][0]=a34;
  a34=arg[1]? arg[1][16] : 0;
  a34=(a9-a34);
  a35=fabs(a34);
  a36=arg[1]? arg[1][23] : 0;
  a36=(a36+a25);
  a36=(a36+a26);
  a35=(a35/a36);
  a37=(a27*a35);
  a37=exp(a37);
  a38=(a35*a37);
  a39=arg[1]? arg[1][17] : 0;
  a39=(a16-a39);
  a40=fabs(a39);
  a41=arg[1]? arg[1][24] : 0;
  a41=(a41+a32);
  a41=(a41+a26);
  a40=(a40/a41);
  a42=(a27*a40);
  a42=exp(a42);
  a43=(a40*a42);
  a38=(a38+a43);
  a43=arg[1]? arg[1][18] : 0;
  a43=(a21-a43);
  a44=fabs(a43);
  a45=arg[1]? arg[1][25] : 0;
  a45=(a45+a26);
  a44=(a44/a45);
  a46=(a27*a44);
  a46=exp(a46);
  a47=(a44*a46);
  a38=(a38+a47);
  a47=(a27*a35);
  a47=exp(a47);
  a48=(a27*a40);
  a48=exp(a48);
  a49=(a47+a48);
  a50=(a27*a44);
  a50=exp(a50);
  a49=(a49+a50);
  a38=(a38/a49);
  a51=(a38+a19);
  if (res[0]!=0) res[0][1]=a51;
  a51=arg[1]? arg[1][26] : 0;
  a9=(a9-a51);
  a51=fabs(a9);
  a52=arg[1]? arg[1][33] : 0;
  a52=(a52+a25);
  a51=(a51/a52);
  a25=(a27*a51);
  a25=exp(a25);
  a53=(a51*a25);
  a54=arg[1]? arg[1][27] : 0;
  a16=(a16-a54);
  a54=fabs(a16);
  a55=arg[1]? arg[1][34] : 0;
  a55=(a55+a32);
  a54=(a54/a55);
  a32=(a27*a54);
  a32=exp(a32);
  a56=(a54*a32);
  a53=(a53+a56);
  a56=arg[1]? arg[1][28] : 0;
  a21=(a21-a56);
  a56=fabs(a21);
  a57=arg[1]? arg[1][35] : 0;
  a57=(a57+a26);
  a56=(a56/a57);
  a26=(a27*a56);
  a26=exp(a26);
  a58=(a56*a26);
  a53=(a53+a58);
  a58=(a27*a51);
  a58=exp(a58);
  a59=(a27*a54);
  a59=exp(a59);
  a60=(a58+a59);
  a61=(a27*a56);
  a61=exp(a61);
  a60=(a60+a61);
  a53=(a53/a60);
  a19=(a53+a19);
  if (res[0]!=0) res[0][2]=a19;
  a19=1.;
  if (res[1]!=0) res[1][0]=a19;
  if (res[1]!=0) res[1][1]=a19;
  if (res[1]!=0) res[1][2]=a19;
  a11=casadi_sign(a11);
  a4=(a11*a4);
  a4=(a4/a24);
  a19=(a28*a4);
  a62=(a27*a4);
  a62=(a28*a62);
  a62=(a23*a62);
  a19=(a19+a62);
  a14=casadi_sign(a14);
  a13=(a14*a13);
  a13=(a13/a31);
  a62=(a33*a13);
  a63=(a27*a13);
  a63=(a33*a63);
  a63=(a5*a63);
  a62=(a62+a63);
  a19=(a19+a62);
  a10=casadi_sign(a10);
  a18=(a10*a18);
  a18=(a18/a8);
  a62=(a1*a18);
  a63=(a27*a18);
  a63=(a1*a63);
  a63=(a22*a63);
  a62=(a62+a63);
  a19=(a19+a62);
  a19=(a19/a2);
  a29=(a29/a2);
  a4=(a27*a4);
  a4=(a3*a4);
  a13=(a27*a13);
  a13=(a17*a13);
  a4=(a4+a13);
  a18=(a27*a18);
  a18=(a0*a18);
  a4=(a4+a18);
  a4=(a29*a4);
  a19=(a19-a4);
  if (res[1]!=0) res[1][3]=a19;
  a34=casadi_sign(a34);
  a34=(a34/a36);
  a36=(a37*a34);
  a19=(a27*a34);
  a37=(a37*a19);
  a35=(a35*a37);
  a36=(a36+a35);
  a36=(a36/a49);
  a38=(a38/a49);
  a34=(a27*a34);
  a47=(a47*a34);
  a47=(a38*a47);
  a36=(a36-a47);
  if (res[1]!=0) res[1][4]=a36;
  a9=casadi_sign(a9);
  a9=(a9/a52);
  a52=(a25*a9);
  a36=(a27*a9);
  a25=(a25*a36);
  a51=(a51*a25);
  a52=(a52+a51);
  a52=(a52/a60);
  a53=(a53/a60);
  a9=(a27*a9);
  a58=(a58*a9);
  a58=(a53*a58);
  a52=(a52-a58);
  if (res[1]!=0) res[1][5]=a52;
  a15=(a11*a15);
  a15=(a15/a24);
  a52=(a28*a15);
  a58=(a27*a15);
  a58=(a28*a58);
  a58=(a23*a58);
  a52=(a52+a58);
  a30=(a14*a30);
  a30=(a30/a31);
  a58=(a33*a30);
  a9=(a27*a30);
  a9=(a33*a9);
  a9=(a5*a9);
  a58=(a58+a9);
  a52=(a52+a58);
  a12=(a10*a12);
  a12=(a12/a8);
  a58=(a1*a12);
  a9=(a27*a12);
  a9=(a1*a9);
  a9=(a22*a9);
  a58=(a58+a9);
  a52=(a52+a58);
  a52=(a52/a2);
  a15=(a27*a15);
  a15=(a3*a15);
  a30=(a27*a30);
  a30=(a17*a30);
  a15=(a15+a30);
  a12=(a27*a12);
  a12=(a0*a12);
  a15=(a15+a12);
  a15=(a29*a15);
  a52=(a52-a15);
  if (res[1]!=0) res[1][6]=a52;
  a39=casadi_sign(a39);
  a39=(a39/a41);
  a41=(a42*a39);
  a52=(a27*a39);
  a42=(a42*a52);
  a40=(a40*a42);
  a41=(a41+a40);
  a41=(a41/a49);
  a39=(a27*a39);
  a48=(a48*a39);
  a48=(a38*a48);
  a41=(a41-a48);
  if (res[1]!=0) res[1][7]=a41;
  a16=casadi_sign(a16);
  a16=(a16/a55);
  a55=(a32*a16);
  a41=(a27*a16);
  a32=(a32*a41);
  a54=(a54*a32);
  a55=(a55+a54);
  a55=(a55/a60);
  a16=(a27*a16);
  a59=(a59*a16);
  a59=(a53*a59);
  a55=(a55-a59);
  if (res[1]!=0) res[1][8]=a55;
  a11=(a11*a20);
  a11=(a11/a24);
  a24=(a28*a11);
  a20=(a27*a11);
  a28=(a28*a20);
  a23=(a23*a28);
  a24=(a24+a23);
  a14=(a14*a7);
  a14=(a14/a31);
  a31=(a33*a14);
  a7=(a27*a14);
  a33=(a33*a7);
  a5=(a5*a33);
  a31=(a31+a5);
  a24=(a24+a31);
  a10=(a10*a6);
  a10=(a10/a8);
  a8=(a1*a10);
  a6=(a27*a10);
  a1=(a1*a6);
  a22=(a22*a1);
  a8=(a8+a22);
  a24=(a24+a8);
  a24=(a24/a2);
  a11=(a27*a11);
  a3=(a3*a11);
  a14=(a27*a14);
  a17=(a17*a14);
  a3=(a3+a17);
  a10=(a27*a10);
  a0=(a0*a10);
  a3=(a3+a0);
  a29=(a29*a3);
  a24=(a24-a29);
  if (res[1]!=0) res[1][9]=a24;
  a43=casadi_sign(a43);
  a43=(a43/a45);
  a45=(a46*a43);
  a24=(a27*a43);
  a46=(a46*a24);
  a44=(a44*a46);
  a45=(a45+a44);
  a45=(a45/a49);
  a43=(a27*a43);
  a50=(a50*a43);
  a38=(a38*a50);
  a45=(a45-a38);
  if (res[1]!=0) res[1][10]=a45;
  a21=casadi_sign(a21);
  a21=(a21/a57);
  a57=(a26*a21);
  a45=(a27*a21);
  a26=(a26*a45);
  a56=(a56*a26);
  a57=(a57+a56);
  a57=(a57/a60);
  a27=(a27*a21);
  a61=(a61*a27);
  a53=(a53*a61);
  a57=(a57-a53);
  if (res[1]!=0) res[1][11]=a57;
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_1_free_mem(int mem) {
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_1_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_1_release(int mem) {
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_1_incref(void) {
}

void FORCESNLPsolverDynDoorObstacle1_inequalities_1_decref(void) {
}

casadi_int FORCESNLPsolverDynDoorObstacle1_inequalities_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynDoorObstacle1_inequalities_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynDoorObstacle1_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynDoorObstacle1_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynDoorObstacle1_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolverDynDoorObstacle1_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
