/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolverDynLiftedObstacle1_model_ ## ID
#endif

#include <math.h> 
#include "FORCESNLPsolverDynLiftedObstacle1_model.h"

#ifndef casadi_real
#define casadi_real FORCESNLPsolverDynLiftedObstacle1_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s10 CASADI_PREFIX(s10)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[40] = {36, 1, 0, 36, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[20] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[7] = {3, 1, 0, 3, 0, 1, 2};
static const casadi_int casadi_s5[25] = {3, 10, 0, 0, 0, 0, 3, 6, 9, 12, 12, 12, 12, 0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2};
static const casadi_int casadi_s6[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s7[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s8[12] = {4, 6, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s9[12] = {6, 6, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5};
static const casadi_int casadi_s10[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* FORCESNLPsolverDynLiftedObstacle1_objective_0:(i0[10],i1[36])->(o0,o1[1x10,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_objective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_objective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_objective_0_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_objective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_objective_0_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_objective_0_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_objective_0_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_objective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_objective_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynLiftedObstacle1_inequalities_0:(i0[10],i1[36])->(o0[3],o1[3x10,12nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[1]? arg[1][6] : 0;
  a1=(a0-a1);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][7] : 0;
  a4=(a3-a4);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][6] : 0;
  a6=arg[1]? arg[1][8] : 0;
  a6=(a5-a6);
  a7=casadi_sq(a6);
  a2=(a2+a7);
  a2=sqrt(a2);
  a7=arg[0]? arg[0][3] : 0;
  a8=(a2+a7);
  if (res[0]!=0) res[0][0]=a8;
  a8=arg[1]? arg[1][16] : 0;
  a8=(a0-a8);
  a9=fabs(a8);
  a10=arg[1]? arg[1][23] : 0;
  a11=5.5000000000000000e-02;
  a10=(a10+a11);
  a12=2.0000000000000000e-02;
  a10=(a10+a12);
  a9=(a9/a10);
  a13=6.;
  a14=(a13*a9);
  a14=exp(a14);
  a15=(a9*a14);
  a16=arg[1]? arg[1][17] : 0;
  a16=(a3-a16);
  a17=fabs(a16);
  a18=arg[1]? arg[1][24] : 0;
  a19=5.0000000000000003e-02;
  a18=(a18+a19);
  a18=(a18+a12);
  a17=(a17/a18);
  a20=(a13*a17);
  a20=exp(a20);
  a21=(a17*a20);
  a15=(a15+a21);
  a21=arg[1]? arg[1][18] : 0;
  a21=(a5-a21);
  a22=fabs(a21);
  a23=arg[1]? arg[1][25] : 0;
  a23=(a23+a12);
  a22=(a22/a23);
  a24=(a13*a22);
  a24=exp(a24);
  a25=(a22*a24);
  a15=(a15+a25);
  a25=(a13*a9);
  a25=exp(a25);
  a26=(a13*a17);
  a26=exp(a26);
  a27=(a25+a26);
  a28=(a13*a22);
  a28=exp(a28);
  a27=(a27+a28);
  a15=(a15/a27);
  a29=(a15+a7);
  if (res[0]!=0) res[0][1]=a29;
  a29=arg[1]? arg[1][26] : 0;
  a0=(a0-a29);
  a29=fabs(a0);
  a30=arg[1]? arg[1][33] : 0;
  a30=(a30+a11);
  a29=(a29/a30);
  a11=(a13*a29);
  a11=exp(a11);
  a31=(a29*a11);
  a32=arg[1]? arg[1][27] : 0;
  a3=(a3-a32);
  a32=fabs(a3);
  a33=arg[1]? arg[1][34] : 0;
  a33=(a33+a19);
  a32=(a32/a33);
  a19=(a13*a32);
  a19=exp(a19);
  a34=(a32*a19);
  a31=(a31+a34);
  a34=arg[1]? arg[1][28] : 0;
  a5=(a5-a34);
  a34=fabs(a5);
  a35=arg[1]? arg[1][35] : 0;
  a35=(a35+a12);
  a34=(a34/a35);
  a12=(a13*a34);
  a12=exp(a12);
  a36=(a34*a12);
  a31=(a31+a36);
  a36=(a13*a29);
  a36=exp(a36);
  a37=(a13*a32);
  a37=exp(a37);
  a38=(a36+a37);
  a39=(a13*a34);
  a39=exp(a39);
  a38=(a38+a39);
  a31=(a31/a38);
  a7=(a31+a7);
  if (res[0]!=0) res[0][2]=a7;
  a7=1.;
  if (res[1]!=0) res[1][0]=a7;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a7;
  a1=(a1/a2);
  if (res[1]!=0) res[1][3]=a1;
  a8=casadi_sign(a8);
  a8=(a8/a10);
  a10=(a14*a8);
  a1=(a13*a8);
  a14=(a14*a1);
  a9=(a9*a14);
  a10=(a10+a9);
  a10=(a10/a27);
  a15=(a15/a27);
  a8=(a13*a8);
  a25=(a25*a8);
  a25=(a15*a25);
  a10=(a10-a25);
  if (res[1]!=0) res[1][4]=a10;
  a0=casadi_sign(a0);
  a0=(a0/a30);
  a30=(a11*a0);
  a10=(a13*a0);
  a11=(a11*a10);
  a29=(a29*a11);
  a30=(a30+a29);
  a30=(a30/a38);
  a31=(a31/a38);
  a0=(a13*a0);
  a36=(a36*a0);
  a36=(a31*a36);
  a30=(a30-a36);
  if (res[1]!=0) res[1][5]=a30;
  a4=(a4/a2);
  if (res[1]!=0) res[1][6]=a4;
  a16=casadi_sign(a16);
  a16=(a16/a18);
  a18=(a20*a16);
  a4=(a13*a16);
  a20=(a20*a4);
  a17=(a17*a20);
  a18=(a18+a17);
  a18=(a18/a27);
  a16=(a13*a16);
  a26=(a26*a16);
  a26=(a15*a26);
  a18=(a18-a26);
  if (res[1]!=0) res[1][7]=a18;
  a3=casadi_sign(a3);
  a3=(a3/a33);
  a33=(a19*a3);
  a18=(a13*a3);
  a19=(a19*a18);
  a32=(a32*a19);
  a33=(a33+a32);
  a33=(a33/a38);
  a3=(a13*a3);
  a37=(a37*a3);
  a37=(a31*a37);
  a33=(a33-a37);
  if (res[1]!=0) res[1][8]=a33;
  a6=(a6/a2);
  if (res[1]!=0) res[1][9]=a6;
  a21=casadi_sign(a21);
  a21=(a21/a23);
  a23=(a24*a21);
  a6=(a13*a21);
  a24=(a24*a6);
  a22=(a22*a24);
  a23=(a23+a22);
  a23=(a23/a27);
  a21=(a13*a21);
  a28=(a28*a21);
  a15=(a15*a28);
  a23=(a23-a15);
  if (res[1]!=0) res[1][10]=a23;
  a5=casadi_sign(a5);
  a5=(a5/a35);
  a35=(a12*a5);
  a23=(a13*a5);
  a12=(a12*a23);
  a34=(a34*a12);
  a35=(a35+a34);
  a35=(a35/a38);
  a13=(a13*a5);
  a39=(a39*a13);
  a31=(a31*a39);
  a35=(a35-a31);
  if (res[1]!=0) res[1][11]=a35;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_0_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_0_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_0_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_0_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynLiftedObstacle1_cdyn_0:(i0[6],i1[4],i2[36])->(o0[6],o1[4x6,3nz],o2[6x6,3nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_n_out(void) { return 3;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_cdyn_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_cdyn_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_cdyn_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_cdyn_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_cdyn_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s8;
    case 2: return casadi_s9;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0:(i0[6],i1[4],i2[36])->(o0[6]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    case 1: return casadi_s7;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s6;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_cdyn_0rd_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynLiftedObstacle1_objective_1:(i0[10],i1[36])->(o0,o1[1x10]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  a11=1.0000000000000001e-01;
  a12=arg[0]? arg[0][7] : 0;
  a13=casadi_sq(a12);
  a13=(a11*a13);
  a2=(a2+a13);
  a13=arg[0]? arg[0][8] : 0;
  a14=casadi_sq(a13);
  a14=(a11*a14);
  a2=(a2+a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=casadi_sq(a14);
  a15=(a11*a15);
  a2=(a2+a15);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  a12=(a12+a12);
  a12=(a11*a12);
  if (res[1]!=0) res[1][7]=a12;
  a13=(a13+a13);
  a13=(a11*a13);
  if (res[1]!=0) res[1][8]=a13;
  a14=(a14+a14);
  a11=(a11*a14);
  if (res[1]!=0) res[1][9]=a11;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_objective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_objective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_objective_1_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_objective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_objective_1_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_objective_1_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_objective_1_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_objective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_objective_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s10;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolverDynLiftedObstacle1_inequalities_1:(i0[10],i1[36])->(o0[3],o1[3x10,12nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a5, a6, a7, a8, a9;
  a0=arg[0]? arg[0][4] : 0;
  a1=arg[1]? arg[1][6] : 0;
  a1=(a0-a1);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][7] : 0;
  a4=(a3-a4);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a5=arg[0]? arg[0][6] : 0;
  a6=arg[1]? arg[1][8] : 0;
  a6=(a5-a6);
  a7=casadi_sq(a6);
  a2=(a2+a7);
  a2=sqrt(a2);
  a7=arg[0]? arg[0][3] : 0;
  a8=(a2+a7);
  if (res[0]!=0) res[0][0]=a8;
  a8=arg[1]? arg[1][16] : 0;
  a8=(a0-a8);
  a9=fabs(a8);
  a10=arg[1]? arg[1][23] : 0;
  a11=5.5000000000000000e-02;
  a10=(a10+a11);
  a12=2.0000000000000000e-02;
  a10=(a10+a12);
  a9=(a9/a10);
  a13=6.;
  a14=(a13*a9);
  a14=exp(a14);
  a15=(a9*a14);
  a16=arg[1]? arg[1][17] : 0;
  a16=(a3-a16);
  a17=fabs(a16);
  a18=arg[1]? arg[1][24] : 0;
  a19=5.0000000000000003e-02;
  a18=(a18+a19);
  a18=(a18+a12);
  a17=(a17/a18);
  a20=(a13*a17);
  a20=exp(a20);
  a21=(a17*a20);
  a15=(a15+a21);
  a21=arg[1]? arg[1][18] : 0;
  a21=(a5-a21);
  a22=fabs(a21);
  a23=arg[1]? arg[1][25] : 0;
  a23=(a23+a12);
  a22=(a22/a23);
  a24=(a13*a22);
  a24=exp(a24);
  a25=(a22*a24);
  a15=(a15+a25);
  a25=(a13*a9);
  a25=exp(a25);
  a26=(a13*a17);
  a26=exp(a26);
  a27=(a25+a26);
  a28=(a13*a22);
  a28=exp(a28);
  a27=(a27+a28);
  a15=(a15/a27);
  a29=(a15+a7);
  if (res[0]!=0) res[0][1]=a29;
  a29=arg[1]? arg[1][26] : 0;
  a0=(a0-a29);
  a29=fabs(a0);
  a30=arg[1]? arg[1][33] : 0;
  a30=(a30+a11);
  a29=(a29/a30);
  a11=(a13*a29);
  a11=exp(a11);
  a31=(a29*a11);
  a32=arg[1]? arg[1][27] : 0;
  a3=(a3-a32);
  a32=fabs(a3);
  a33=arg[1]? arg[1][34] : 0;
  a33=(a33+a19);
  a32=(a32/a33);
  a19=(a13*a32);
  a19=exp(a19);
  a34=(a32*a19);
  a31=(a31+a34);
  a34=arg[1]? arg[1][28] : 0;
  a5=(a5-a34);
  a34=fabs(a5);
  a35=arg[1]? arg[1][35] : 0;
  a35=(a35+a12);
  a34=(a34/a35);
  a12=(a13*a34);
  a12=exp(a12);
  a36=(a34*a12);
  a31=(a31+a36);
  a36=(a13*a29);
  a36=exp(a36);
  a37=(a13*a32);
  a37=exp(a37);
  a38=(a36+a37);
  a39=(a13*a34);
  a39=exp(a39);
  a38=(a38+a39);
  a31=(a31/a38);
  a7=(a31+a7);
  if (res[0]!=0) res[0][2]=a7;
  a7=1.;
  if (res[1]!=0) res[1][0]=a7;
  if (res[1]!=0) res[1][1]=a7;
  if (res[1]!=0) res[1][2]=a7;
  a1=(a1/a2);
  if (res[1]!=0) res[1][3]=a1;
  a8=casadi_sign(a8);
  a8=(a8/a10);
  a10=(a14*a8);
  a1=(a13*a8);
  a14=(a14*a1);
  a9=(a9*a14);
  a10=(a10+a9);
  a10=(a10/a27);
  a15=(a15/a27);
  a8=(a13*a8);
  a25=(a25*a8);
  a25=(a15*a25);
  a10=(a10-a25);
  if (res[1]!=0) res[1][4]=a10;
  a0=casadi_sign(a0);
  a0=(a0/a30);
  a30=(a11*a0);
  a10=(a13*a0);
  a11=(a11*a10);
  a29=(a29*a11);
  a30=(a30+a29);
  a30=(a30/a38);
  a31=(a31/a38);
  a0=(a13*a0);
  a36=(a36*a0);
  a36=(a31*a36);
  a30=(a30-a36);
  if (res[1]!=0) res[1][5]=a30;
  a4=(a4/a2);
  if (res[1]!=0) res[1][6]=a4;
  a16=casadi_sign(a16);
  a16=(a16/a18);
  a18=(a20*a16);
  a4=(a13*a16);
  a20=(a20*a4);
  a17=(a17*a20);
  a18=(a18+a17);
  a18=(a18/a27);
  a16=(a13*a16);
  a26=(a26*a16);
  a26=(a15*a26);
  a18=(a18-a26);
  if (res[1]!=0) res[1][7]=a18;
  a3=casadi_sign(a3);
  a3=(a3/a33);
  a33=(a19*a3);
  a18=(a13*a3);
  a19=(a19*a18);
  a32=(a32*a19);
  a33=(a33+a32);
  a33=(a33/a38);
  a3=(a13*a3);
  a37=(a37*a3);
  a37=(a31*a37);
  a33=(a33-a37);
  if (res[1]!=0) res[1][8]=a33;
  a6=(a6/a2);
  if (res[1]!=0) res[1][9]=a6;
  a21=casadi_sign(a21);
  a21=(a21/a23);
  a23=(a24*a21);
  a6=(a13*a21);
  a24=(a24*a6);
  a22=(a22*a24);
  a23=(a23+a22);
  a23=(a23/a27);
  a21=(a13*a21);
  a28=(a28*a21);
  a15=(a15*a28);
  a23=(a23-a15);
  if (res[1]!=0) res[1][10]=a23;
  a5=casadi_sign(a5);
  a5=(a5/a35);
  a35=(a12*a5);
  a23=(a13*a5);
  a12=(a12*a23);
  a34=(a34*a12);
  a35=(a35+a34);
  a35=(a35/a38);
  a13=(a13*a5);
  a39=(a39*a13);
  a31=(a31*a39);
  a35=(a35-a31);
  if (res[1]!=0) res[1][11]=a35;
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_1_free_mem(int mem) {
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_checkout(void) {
  return 0;
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_1_release(int mem) {
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_1_incref(void) {
}

void FORCESNLPsolverDynLiftedObstacle1_inequalities_1_decref(void) {
}

casadi_int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolverDynLiftedObstacle1_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolverDynLiftedObstacle1_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolverDynLiftedObstacle1_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s4;
    case 1: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolverDynLiftedObstacle1_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
