/*
FORCESNLPsolverDynObstacle1 : A fast customized optimization solver.

Copyright (C) 2013-2023 EMBOTECH AG [info@embotech.com]. All rights reserved.


This software is intended for simulation and testing purposes only. 
Use of this software for any commercial purpose is prohibited.

This program is distributed in the hope that it will be useful.
EMBOTECH makes NO WARRANTIES with respect to the use of the software 
without even the implied warranty of MERCHANTABILITY or FITNESS FOR A 
PARTICULAR PURPOSE. 

EMBOTECH shall not have any liability for any damage arising from the use
of the software.

This Agreement shall exclusively be governed by and interpreted in 
accordance with the laws of Switzerland, excluding its principles
of conflict of laws. The Courts of Zurich-City shall have exclusive 
jurisdiction in case of any dispute.

*/

/* Generated by FORCESPRO v6.2.0 on Monday, December 18, 2023 at 9:03:37 AM */
#ifndef FORCESNLPsolverDynObstacle1_MEMORY_H
#define FORCESNLPsolverDynObstacle1_MEMORY_H

#include "FORCESNLPsolverDynObstacle1.h"


/* MEMORY STRUCT --------------------------------------------------------*/

#ifdef __cplusplus
extern "C" {
#endif
extern FORCESNLPsolverDynObstacle1_mem * FORCESNLPsolverDynObstacle1_internal_mem(solver_int32_unsigned i_mem);
#ifdef __cplusplus
}
#endif
#endif /* MEMORY_H */
