/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) FORCESNLPsolver3DTargetObstacle1_model_ ## ID
#endif

#include <math.h> 
#include "FORCESNLPsolver3DTargetObstacle1_model.h"

#ifndef casadi_real
#define casadi_real FORCESNLPsolver3DTargetObstacle1_float
#endif

#ifndef casadi_int
#define casadi_int solver_int32_default
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_f1 CASADI_PREFIX(f1)
#define casadi_f2 CASADI_PREFIX(f2)
#define casadi_f3 CASADI_PREFIX(f3)
#define casadi_f4 CASADI_PREFIX(f4)
#define casadi_f5 CASADI_PREFIX(f5)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_s4 CASADI_PREFIX(s4)
#define casadi_s5 CASADI_PREFIX(s5)
#define casadi_s6 CASADI_PREFIX(s6)
#define casadi_s7 CASADI_PREFIX(s7)
#define casadi_s8 CASADI_PREFIX(s8)
#define casadi_s9 CASADI_PREFIX(s9)
#define casadi_sign CASADI_PREFIX(sign)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#if 0
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

casadi_real casadi_sq(casadi_real x) { return x*x;}

casadi_real casadi_sign(casadi_real x) { return x<0 ? -1 : x>0 ? 1 : x;}

static const casadi_int casadi_s0[14] = {10, 1, 0, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9};
static const casadi_int casadi_s1[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};
static const casadi_int casadi_s2[5] = {1, 1, 0, 1, 0};
static const casadi_int casadi_s3[20] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 7, 7, 7, 0, 0, 0, 0, 0, 0, 0};
static const casadi_int casadi_s4[17] = {1, 10, 0, 0, 0, 0, 1, 2, 3, 4, 4, 4, 4, 0, 0, 0, 0};
static const casadi_int casadi_s5[10] = {6, 1, 0, 6, 0, 1, 2, 3, 4, 5};
static const casadi_int casadi_s6[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s7[12] = {4, 6, 0, 0, 0, 0, 1, 2, 3, 0, 1, 2};
static const casadi_int casadi_s8[12] = {6, 6, 0, 1, 2, 3, 3, 3, 3, 3, 4, 5};
static const casadi_int casadi_s9[23] = {1, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0};

/* FORCESNLPsolver3DTargetObstacle1_objective_0:(i0[10],i1[16])->(o0,o1[1x10,7nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_objective_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_objective_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_objective_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_objective_0_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_objective_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_objective_0_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_objective_0_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_objective_0_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_objective_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver3DTargetObstacle1_objective_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolver3DTargetObstacle1_objective_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_objective_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_objective_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_objective_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_objective_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s3;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_objective_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver3DTargetObstacle1_inequalities_0:(i0[10],i1[16])->(o0,o1[1x10,4nz]) */
static int casadi_f1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][10] : 0;
  a1=casadi_sq(a0);
  a2=arg[1]? arg[1][11] : 0;
  a3=casadi_sq(a2);
  a4=(a1-a3);
  a5=arg[1]? arg[1][12] : 0;
  a6=casadi_sq(a5);
  a4=(a4-a6);
  a7=arg[1]? arg[1][9] : 0;
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a9=arg[0]? arg[0][4] : 0;
  a10=arg[1]? arg[1][6] : 0;
  a9=(a9-a10);
  a10=(a4*a9);
  a11=2.;
  a12=(a0*a2);
  a13=(a5*a7);
  a14=(a12-a13);
  a14=(a11*a14);
  a15=arg[0]? arg[0][5] : 0;
  a16=arg[1]? arg[1][7] : 0;
  a15=(a15-a16);
  a16=(a14*a15);
  a10=(a10+a16);
  a16=(a0*a5);
  a17=(a2*a7);
  a18=(a16+a17);
  a18=(a11*a18);
  a19=arg[0]? arg[0][6] : 0;
  a20=arg[1]? arg[1][8] : 0;
  a19=(a19-a20);
  a20=(a18*a19);
  a10=(a10+a20);
  a20=fabs(a10);
  a21=arg[1]? arg[1][13] : 0;
  a22=5.5000000000000000e-02;
  a21=(a21+a22);
  a22=2.0000000000000000e-02;
  a21=(a21+a22);
  a20=(a20/a21);
  a23=6.;
  a24=(a23*a20);
  a24=exp(a24);
  a25=(a20*a24);
  a12=(a12+a13);
  a12=(a11*a12);
  a13=(a12*a9);
  a26=(a3-a1);
  a26=(a26-a6);
  a26=(a26+a8);
  a27=(a26*a15);
  a13=(a13+a27);
  a2=(a2*a5);
  a0=(a0*a7);
  a7=(a2-a0);
  a7=(a11*a7);
  a5=(a7*a19);
  a13=(a13+a5);
  a5=fabs(a13);
  a27=arg[1]? arg[1][14] : 0;
  a28=5.0000000000000003e-02;
  a27=(a27+a28);
  a27=(a27+a22);
  a5=(a5/a27);
  a28=(a23*a5);
  a28=exp(a28);
  a29=(a5*a28);
  a25=(a25+a29);
  a16=(a16-a17);
  a16=(a11*a16);
  a9=(a16*a9);
  a2=(a2+a0);
  a11=(a11*a2);
  a15=(a11*a15);
  a9=(a9+a15);
  a1=(a1+a3);
  a6=(a6-a1);
  a6=(a6+a8);
  a19=(a6*a19);
  a9=(a9+a19);
  a19=fabs(a9);
  a8=arg[1]? arg[1][15] : 0;
  a8=(a8+a22);
  a19=(a19/a8);
  a22=(a23*a19);
  a22=exp(a22);
  a1=(a19*a22);
  a25=(a25+a1);
  a1=(a23*a20);
  a1=exp(a1);
  a3=(a23*a5);
  a3=exp(a3);
  a15=(a1+a3);
  a2=(a23*a19);
  a2=exp(a2);
  a15=(a15+a2);
  a25=(a25/a15);
  a0=arg[0]? arg[0][3] : 0;
  a0=(a25+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  a9=casadi_sign(a9);
  a0=(a22/a15);
  a25=(a25/a15);
  a2=(a2*a25);
  a2=(a23*a2);
  a0=(a0-a2);
  a19=(a19/a15);
  a22=(a22*a19);
  a22=(a23*a22);
  a0=(a0+a22);
  a0=(a0/a8);
  a9=(a9*a0);
  a16=(a16*a9);
  a13=casadi_sign(a13);
  a0=(a28/a15);
  a3=(a3*a25);
  a3=(a23*a3);
  a0=(a0-a3);
  a5=(a5/a15);
  a28=(a28*a5);
  a28=(a23*a28);
  a0=(a0+a28);
  a0=(a0/a27);
  a13=(a13*a0);
  a12=(a12*a13);
  a16=(a16+a12);
  a10=casadi_sign(a10);
  a12=(a24/a15);
  a1=(a1*a25);
  a1=(a23*a1);
  a12=(a12-a1);
  a20=(a20/a15);
  a24=(a24*a20);
  a23=(a23*a24);
  a12=(a12+a23);
  a12=(a12/a21);
  a10=(a10*a12);
  a4=(a4*a10);
  a16=(a16+a4);
  if (res[1]!=0) res[1][1]=a16;
  a11=(a11*a9);
  a26=(a26*a13);
  a11=(a11+a26);
  a14=(a14*a10);
  a11=(a11+a14);
  if (res[1]!=0) res[1][2]=a11;
  a6=(a6*a9);
  a7=(a7*a13);
  a6=(a6+a7);
  a18=(a18*a10);
  a6=(a6+a18);
  if (res[1]!=0) res[1][3]=a6;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f1(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_0_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_0_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_0_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_0_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_inequalities_0_n_in(void) { return 2;}

casadi_int FORCESNLPsolver3DTargetObstacle1_inequalities_0_n_out(void) { return 2;}

casadi_real FORCESNLPsolver3DTargetObstacle1_inequalities_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_inequalities_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_inequalities_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_inequalities_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_inequalities_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver3DTargetObstacle1_cdyn_0:(i0[6],i1[4],i2[16])->(o0[6],o1[4x6,3nz],o2[6x6,3nz]) */
static int casadi_f2(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  if (res[1]!=0) res[1][1]=a0;
  if (res[1]!=0) res[1][2]=a0;
  if (res[2]!=0) res[2][0]=a0;
  if (res[2]!=0) res[2][1]=a0;
  if (res[2]!=0) res[2][2]=a0;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f2(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_cdyn_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolver3DTargetObstacle1_cdyn_0_n_out(void) { return 3;}

casadi_real FORCESNLPsolver3DTargetObstacle1_cdyn_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_cdyn_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_cdyn_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    case 2: return "o2";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_cdyn_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_cdyn_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s7;
    case 2: return casadi_s8;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 3;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0:(i0[6],i1[4],i2[16])->(o0[6]) */
static int casadi_f3(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0;
  a0=arg[0]? arg[0][3] : 0;
  if (res[0]!=0) res[0][0]=a0;
  a0=arg[0]? arg[0][4] : 0;
  if (res[0]!=0) res[0][1]=a0;
  a0=arg[0]? arg[0][5] : 0;
  if (res[0]!=0) res[0][2]=a0;
  a0=arg[1]? arg[1][0] : 0;
  if (res[0]!=0) res[0][3]=a0;
  a0=arg[1]? arg[1][1] : 0;
  if (res[0]!=0) res[0][4]=a0;
  a0=arg[1]? arg[1][2] : 0;
  if (res[0]!=0) res[0][5]=a0;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f3(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_n_in(void) { return 3;}

casadi_int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_n_out(void) { return 1;}

casadi_real FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    case 1: return casadi_s6;
    case 2: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s5;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_cdyn_0rd_0_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver3DTargetObstacle1_objective_1:(i0[10],i1[16])->(o0,o1[1x10]) */
static int casadi_f4(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a2, a3, a4, a5, a6, a7, a8, a9;
  a0=390.;
  a1=arg[0]? arg[0][4] : 0;
  a2=arg[1]? arg[1][0] : 0;
  a1=(a1-a2);
  a2=casadi_sq(a1);
  a3=arg[0]? arg[0][5] : 0;
  a4=arg[1]? arg[1][1] : 0;
  a3=(a3-a4);
  a4=casadi_sq(a3);
  a2=(a2+a4);
  a4=arg[0]? arg[0][6] : 0;
  a5=arg[1]? arg[1][2] : 0;
  a4=(a4-a5);
  a5=casadi_sq(a4);
  a2=(a2+a5);
  a2=(a0*a2);
  a5=1.0000000000000000e-02;
  a6=arg[0]? arg[0][0] : 0;
  a7=30.;
  a6=(a6/a7);
  a8=casadi_sq(a6);
  a8=(a5*a8);
  a2=(a2+a8);
  a8=arg[0]? arg[0][1] : 0;
  a8=(a8/a7);
  a9=casadi_sq(a8);
  a9=(a5*a9);
  a2=(a2+a9);
  a9=arg[0]? arg[0][2] : 0;
  a9=(a9/a7);
  a7=casadi_sq(a9);
  a7=(a5*a7);
  a2=(a2+a7);
  a7=1000.;
  a10=arg[0]? arg[0][3] : 0;
  a11=casadi_sq(a10);
  a11=(a7*a11);
  a2=(a2+a11);
  a11=1.0000000000000001e-01;
  a12=arg[0]? arg[0][7] : 0;
  a13=casadi_sq(a12);
  a13=(a11*a13);
  a2=(a2+a13);
  a13=arg[0]? arg[0][8] : 0;
  a14=casadi_sq(a13);
  a14=(a11*a14);
  a2=(a2+a14);
  a14=arg[0]? arg[0][9] : 0;
  a15=casadi_sq(a14);
  a15=(a11*a15);
  a2=(a2+a15);
  if (res[0]!=0) res[0][0]=a2;
  a2=3.3333333333333333e-02;
  a6=(a6+a6);
  a6=(a5*a6);
  a6=(a2*a6);
  if (res[1]!=0) res[1][0]=a6;
  a8=(a8+a8);
  a8=(a5*a8);
  a8=(a2*a8);
  if (res[1]!=0) res[1][1]=a8;
  a9=(a9+a9);
  a5=(a5*a9);
  a2=(a2*a5);
  if (res[1]!=0) res[1][2]=a2;
  a10=(a10+a10);
  a7=(a7*a10);
  if (res[1]!=0) res[1][3]=a7;
  a1=(a1+a1);
  a1=(a0*a1);
  if (res[1]!=0) res[1][4]=a1;
  a3=(a3+a3);
  a3=(a0*a3);
  if (res[1]!=0) res[1][5]=a3;
  a4=(a4+a4);
  a0=(a0*a4);
  if (res[1]!=0) res[1][6]=a0;
  a12=(a12+a12);
  a12=(a11*a12);
  if (res[1]!=0) res[1][7]=a12;
  a13=(a13+a13);
  a13=(a11*a13);
  if (res[1]!=0) res[1][8]=a13;
  a14=(a14+a14);
  a11=(a11*a14);
  if (res[1]!=0) res[1][9]=a11;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_objective_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f4(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_objective_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_objective_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_objective_1_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_objective_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_objective_1_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_objective_1_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_objective_1_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_objective_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver3DTargetObstacle1_objective_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolver3DTargetObstacle1_objective_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_objective_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_objective_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_objective_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_objective_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s9;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_objective_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}

/* FORCESNLPsolver3DTargetObstacle1_inequalities_1:(i0[10],i1[16])->(o0,o1[1x10,4nz]) */
static int casadi_f5(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a4, a5, a6, a7, a8, a9;
  a0=arg[1]? arg[1][10] : 0;
  a1=casadi_sq(a0);
  a2=arg[1]? arg[1][11] : 0;
  a3=casadi_sq(a2);
  a4=(a1-a3);
  a5=arg[1]? arg[1][12] : 0;
  a6=casadi_sq(a5);
  a4=(a4-a6);
  a7=arg[1]? arg[1][9] : 0;
  a8=casadi_sq(a7);
  a4=(a4+a8);
  a9=arg[0]? arg[0][4] : 0;
  a10=arg[1]? arg[1][6] : 0;
  a9=(a9-a10);
  a10=(a4*a9);
  a11=2.;
  a12=(a0*a2);
  a13=(a5*a7);
  a14=(a12-a13);
  a14=(a11*a14);
  a15=arg[0]? arg[0][5] : 0;
  a16=arg[1]? arg[1][7] : 0;
  a15=(a15-a16);
  a16=(a14*a15);
  a10=(a10+a16);
  a16=(a0*a5);
  a17=(a2*a7);
  a18=(a16+a17);
  a18=(a11*a18);
  a19=arg[0]? arg[0][6] : 0;
  a20=arg[1]? arg[1][8] : 0;
  a19=(a19-a20);
  a20=(a18*a19);
  a10=(a10+a20);
  a20=fabs(a10);
  a21=arg[1]? arg[1][13] : 0;
  a22=5.5000000000000000e-02;
  a21=(a21+a22);
  a22=2.0000000000000000e-02;
  a21=(a21+a22);
  a20=(a20/a21);
  a23=6.;
  a24=(a23*a20);
  a24=exp(a24);
  a25=(a20*a24);
  a12=(a12+a13);
  a12=(a11*a12);
  a13=(a12*a9);
  a26=(a3-a1);
  a26=(a26-a6);
  a26=(a26+a8);
  a27=(a26*a15);
  a13=(a13+a27);
  a2=(a2*a5);
  a0=(a0*a7);
  a7=(a2-a0);
  a7=(a11*a7);
  a5=(a7*a19);
  a13=(a13+a5);
  a5=fabs(a13);
  a27=arg[1]? arg[1][14] : 0;
  a28=5.0000000000000003e-02;
  a27=(a27+a28);
  a27=(a27+a22);
  a5=(a5/a27);
  a28=(a23*a5);
  a28=exp(a28);
  a29=(a5*a28);
  a25=(a25+a29);
  a16=(a16-a17);
  a16=(a11*a16);
  a9=(a16*a9);
  a2=(a2+a0);
  a11=(a11*a2);
  a15=(a11*a15);
  a9=(a9+a15);
  a1=(a1+a3);
  a6=(a6-a1);
  a6=(a6+a8);
  a19=(a6*a19);
  a9=(a9+a19);
  a19=fabs(a9);
  a8=arg[1]? arg[1][15] : 0;
  a8=(a8+a22);
  a19=(a19/a8);
  a22=(a23*a19);
  a22=exp(a22);
  a1=(a19*a22);
  a25=(a25+a1);
  a1=(a23*a20);
  a1=exp(a1);
  a3=(a23*a5);
  a3=exp(a3);
  a15=(a1+a3);
  a2=(a23*a19);
  a2=exp(a2);
  a15=(a15+a2);
  a25=(a25/a15);
  a0=arg[0]? arg[0][3] : 0;
  a0=(a25+a0);
  if (res[0]!=0) res[0][0]=a0;
  a0=1.;
  if (res[1]!=0) res[1][0]=a0;
  a9=casadi_sign(a9);
  a0=(a22/a15);
  a25=(a25/a15);
  a2=(a2*a25);
  a2=(a23*a2);
  a0=(a0-a2);
  a19=(a19/a15);
  a22=(a22*a19);
  a22=(a23*a22);
  a0=(a0+a22);
  a0=(a0/a8);
  a9=(a9*a0);
  a16=(a16*a9);
  a13=casadi_sign(a13);
  a0=(a28/a15);
  a3=(a3*a25);
  a3=(a23*a3);
  a0=(a0-a3);
  a5=(a5/a15);
  a28=(a28*a5);
  a28=(a23*a28);
  a0=(a0+a28);
  a0=(a0/a27);
  a13=(a13*a0);
  a12=(a12*a13);
  a16=(a16+a12);
  a10=casadi_sign(a10);
  a12=(a24/a15);
  a1=(a1*a25);
  a1=(a23*a1);
  a12=(a12-a1);
  a20=(a20/a15);
  a24=(a24*a20);
  a23=(a23*a24);
  a12=(a12+a23);
  a12=(a12/a21);
  a10=(a10*a12);
  a4=(a4*a10);
  a16=(a16+a4);
  if (res[1]!=0) res[1][1]=a16;
  a11=(a11*a9);
  a26=(a26*a13);
  a11=(a11+a26);
  a14=(a14*a10);
  a11=(a11+a14);
  if (res[1]!=0) res[1][2]=a11;
  a6=(a6*a9);
  a7=(a7*a13);
  a6=(a6+a7);
  a18=(a18*a10);
  a6=(a6+a18);
  if (res[1]!=0) res[1][3]=a6;
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_1(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f5(arg, res, iw, w, mem);
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_1_alloc_mem(void) {
  return 0;
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_1_init_mem(int mem) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_1_free_mem(int mem) {
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_1_checkout(void) {
  return 0;
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_1_release(int mem) {
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_1_incref(void) {
}

void FORCESNLPsolver3DTargetObstacle1_inequalities_1_decref(void) {
}

casadi_int FORCESNLPsolver3DTargetObstacle1_inequalities_1_n_in(void) { return 2;}

casadi_int FORCESNLPsolver3DTargetObstacle1_inequalities_1_n_out(void) { return 2;}

casadi_real FORCESNLPsolver3DTargetObstacle1_inequalities_1_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_inequalities_1_name_in(casadi_int i){
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    default: return 0;
  }
}

const char* FORCESNLPsolver3DTargetObstacle1_inequalities_1_name_out(casadi_int i){
  switch (i) {
    case 0: return "o0";
    case 1: return "o1";
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_inequalities_1_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    default: return 0;
  }
}

const casadi_int* FORCESNLPsolver3DTargetObstacle1_inequalities_1_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s2;
    case 1: return casadi_s4;
    default: return 0;
  }
}

int FORCESNLPsolver3DTargetObstacle1_inequalities_1_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 2;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
